name: Verify Signatures with Gitsign

on:
  push:
    branches:
      - main

env:
  IMAGE_REGISTRY: quay.io
  IMAGE_REPO: lucarval/festoji
  IMAGE_TAGS: latest
  APPS_DOMAIN: apps.tas-pentest.v5k1.p1.openshiftapps.com
  TUF_URL: https://tuf-tas-test.apps.tas-pentest.v5k1.p1.openshiftapps.com
  OIDC_ISSUER_URL: https://token.actions.githubusercontent.com
  COSIGN_FULCIO_URL: https://fulcio-server-tas-test.apps.tas-pentest.v5k1.p1.openshiftapps.com
  COSIGN_REKOR_URL: https://rekor-server-tas-test.apps.tas-pentest.v5k1.p1.openshiftapps.com
  COSIGN_MIRROR: https://tuf-tas-test.apps.tas-pentest.v5k1.p1.openshiftapps.com
  COSIGN_ROOT: https://tuf-tas-test.apps.tas-pentest.v5k1.p1.openshiftapps.com/root.json
  COSIGN_OIDC_ISSUER: https://token.actions.githubusercontent.com
  COSIGN_CERTIFICATE_OIDC_ISSUER: https://token.actions.githubusercontent.com
  SIGSTORE_FULCIO_URL: https://fulcio-server-tas-test.apps.tas-pentest.v5k1.p1.openshiftapps.com
  SIGSTORE_REKOR_URL: https://rekor-server-tas-test.apps.tas-pentest.v5k1.p1.openshiftapps.com
  REKOR_REKOR_SERVER: https://rekor-server-tas-test.apps.tas-pentest.v5k1.p1.openshiftapps.com
  GITSIGN_OIDC_ISSUER: https://keycloak-keycloak-system.apps.tas-pentest.v5k1.p1.openshiftapps.com/auth/realms/sigstore
  TAS_IMAGE: quay.io/vedadashan2/tastest0502:latest

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # This is required to request the OIDC token
      contents: read   # This is required for actions/checkout

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: main

    - name: Build project
      run: |
        mkdir -p dist
        echo "Example artifact" > dist/artifact.txt

    - name: Install Gitsign
      shell: bash
      run: |
        set -ex
        curl -fsL https://cli-server-trusted-artifact-signer.$APPS_DOMAIN/clients/linux/gitsign-amd64.gz -o /usr/local/bin/gitsign-amd64.gz
        gunzip /usr/local/bin/gitsign-amd64.gz
        chmod +x /usr/local/bin/gitsign-amd64
        mv /usr/local/bin/gitsign-amd64 /usr/local/bin/gitsign
        curl -fsL https://cli-server-trusted-artifact-signer.$APPS_DOMAIN/clients/linux/cosign-amd64.gz -o /usr/local/bin/cosign-amd64.gz
        gunzip /usr/local/bin/cosign-amd64.gz
        chmod +x /usr/local/bin/cosign-amd64
        mv /usr/local/bin/cosign-amd64 /usr/local/bin/cosign

    - name: Initialize Gitsign
      shell: bash
      run: gitsign initialize --mirror=$TUF_URL --root=$TUF_URL/root.json

    - name: Verify Gitsign Installation
      shell: bash
      run: |
        which gitsign
        ls -l /usr/local/bin/gitsign
        gitsign version

    - name: Verify Commit Signatures
      shell: bash
      run: |
        gitsign verify --certificate-identity=vedadashan@gmail.com --certificate-oidc-issuer=$GITSIGN_OIDC_ISSUER HEAD

    - name: Request OIDC token
      id: oidc-token
      run: |
        echo "Requesting OIDC token..."
        echo "Token: ${{ steps.auth.outputs.id_token }}"
      env:
        ACTIONS_ID_TOKEN_REQUEST_URL: ${{ secrets.ACTIONS_ID_TOKEN_REQUEST_URL }}
        ACTIONS_ID_TOKEN_REQUEST_TOKEN: ${{ secrets.ACTIONS_ID_TOKEN_REQUEST_TOKEN }}

    - name: Use OIDC token with Sigstore
      run: |
        echo ${{ secrets.ACTIONS_ID_TOKEN_REQUEST_URL }}
        echo ${{ steps.oidc-token.outputs.id_token }}
        echo ${{ secrets.ACTIONS_ID_TOKEN_REQUEST_TOKEN }}
        cosign initialize --mirror=$TUF_URL --root=$TUF_URL/root.json
        cosign login quay.io -u vedadashan2+vedadashan2 -p 1RHTW7CFVKWZ1YMG8SO6CGPP0FKHAI7WT49PGRC3VGJ5P9QD3GCKIHAN5FGR936G 
        cosign sign --rekor-url $SIGSTORE_REKOR_URL --oidc-issuer ${{ secrets.ACTIONS_ID_TOKEN_REQUEST_URL }} --identity-token ${{ steps.oidc-token.outputs.id_token }} $TAS_IMAGE

